#!/bin/bash
set -uo pipefail


################################################
# Initialize script environment

# Find the directory this script is stored in. (from: http://stackoverflow.com/questions/59895)
function get_source_dir() {
	local source="${BASH_SOURCE[0]}"
	while [[ -h $source ]]
	do
		local tmp
		tmp="$(cd -P "$(dirname "${source}")" && pwd)"
		source="$(readlink "${source}")"
		[[ $source != /* ]] && source="${tmp}/${source}"
	done

	echo -n "$(realpath "$(dirname "${source}")")"
}

ACTUAL_WORKING_DIRECTORY="$(realpath "$(pwd)")" || exit 1
export ACTUAL_WORKING_DIRECTORY
GENTOO_INSTALL_REPO_DIR_ORIGINAL="$(get_source_dir)"
export GENTOO_INSTALL_REPO_DIR_ORIGINAL
export GENTOO_INSTALL_REPO_DIR="$GENTOO_INSTALL_REPO_DIR_ORIGINAL"
export GENTOO_INSTALL_REPO_SCRIPT_ACTIVE=true
export GENTOO_INSTALL_REPO_SCRIPT_PID=$$

umask 0077

# shellcheck source=./scripts/utils.sh
source "$GENTOO_INSTALL_REPO_DIR/scripts/utils.sh"
# shellcheck source=./scripts/config.sh
source "$GENTOO_INSTALL_REPO_DIR/scripts/config.sh"
# shellcheck source=./scripts/functions.sh
source "$GENTOO_INSTALL_REPO_DIR/scripts/functions.sh"
# shellcheck source=./scripts/main.sh
source "$GENTOO_INSTALL_REPO_DIR/scripts/main.sh"


################################################
# Main dispatch

# Instantly kill when pressing ctrl-c
trap 'kill "$GENTOO_INSTALL_REPO_SCRIPT_PID"' INT

ACTION=""
CONFIG="$GENTOO_INSTALL_REPO_DIR/gentoo.conf"

while [[ $# -gt 0 ]]; do
	case "$1" in
		""|"help"|"--help"|"-help"|"-h")
			echo "用法: $0 [opts]... <action>"
			echo "進行 Gentoo 最小安裝。 參見 https://github.com/zozx/gentoo-install-zh"
			echo "以獲取更多資訊。若配置文件不存在，配置器將啟動"
			echo ""
			echo "選項:"
			echo "  -c, --config <CONFIG>           使用所提供的配置文件而非預設"
			echo "                                  位置 (gentoo.conf) 。 初始配置一併應用於安裝，以防該文件不存在"
			echo ""
			echo "Actions:"
			echo "  -i, --install                 如已配置般安裝 Gentoo 。若所提供之配置文件存在，則此為預設模式"
			echo "  -R, --chroot <DIR> [CMD...]   chroot 進入已有系統。根文件系統"
			echo "                                  必須已在 DIR 下被掛載。全部所需的特殊文件系統"
			echo "                                  將被掛載於其中, 並於 chroot 退出時被解除掛載。"
			exit 0
			;;
		"-c"|"--config")
			[[ -f "$2" ]] \
				|| die "找不到配置文件 : '$2'"
			CONFIG="$(cd "$ACTUAL_WORKING_DIRECTORY" && realpath --relative-to="$GENTOO_INSTALL_REPO_DIR" "$2" 2>/dev/null)" || die "無法確定配置的真實路徑"
			shift
			;;
		"-R"|"--chroot")
			[[ -z $ACTION ]] || die "多重操作"
			ACTION="chroot"
			CHROOT_DIR="$2"
			[[ -e "$CHROOT_DIR" ]] || die "找不到 chroot 路徑 : '$CHROOT_DIR'"
			shift
			;;
		"-i"|"--install")
			[[ -z $ACTION ]] || die "多重操作"
			ACTION="install"
			;;
		"__install_gentoo_in_chroot")
			ACTION="__install_gentoo_in_chroot"
			;;
		*) die "無效選項 '$1'" ;;
	esac
	shift
done

# Check configuration location
[[ -z "${CONFIG%%"$GENTOO_INSTALL_REPO_DIR"*}" ]] \
	|| die "配置文件必須在安裝目錄內。這是必要的，以使之於 chroot 環境內可以訪問。"

if [[ -z "$ACTION" ]]; then
	if [[ -e "$CONFIG" ]]; then
		# Default if configuration exists: Run installer
		ACTION="install"
	else
		# Default if configuration does not exist: Run configurator, and exit afterwards.
		echo "gentoo.conf 尚未被創建。 開啟配置器而非安裝。"
		exec "$GENTOO_INSTALL_REPO_DIR/configure" "$CONFIG"
	fi
fi

if [[ "$ACTION" != "chroot" ]]; then
	# Load config if we aren't just chrooting
	[[ -e "$CONFIG" ]] \
		 || die "配置文件 '$CONFIG' 不存在。 添加 '-i' 或運行 ./configure 以啟動配置器。"

	# shellcheck disable=SC1090
	source "$CONFIG" || die "無法應用配置"
	[[ $I_HAVE_READ_AND_EDITED_THE_CONFIG_PROPERLY == "true" ]] \
		|| die "閣下尚未正確地閱讀配置。請編輯配置文件並設定 I_HAVE_READ_AND_EDITED_THE_CONFIG_PROPERLY=true 以繼續。"

	preprocess_config
fi

[[ $EUID == 0 ]] \
	|| die "該程式須由 root 運行"

mkdir_or_die 0755 "$TMP_DIR"

case "$ACTION" in
	"chroot")  main_chroot "$CHROOT_DIR" "$@" ;;
	"install") main_install "$@" ;;
	"__install_gentoo_in_chroot") main_install_gentoo_in_chroot "$@" ;;
	*) die "無效操作 '$ACTION'" ;;
esac
